services:
   
  reverse_proxy:
    build:      
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${REVERSE_PROXY_PORT}:80"
    networks:
      - proxynet
      
  frontend:
    build:      
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_HOST_PORT}:80"
    depends_on:
      - backend
    networks:
      - frontend
      - proxynet
      
  backend:
    build:      
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "${BACKEND_HOST_PORT}:8080"
    environment:
      - DATABASE_SERVER=${DATABASE_SERVER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_PORT=${DATABASE_HOST_PORT}
    depends_on:
      - database
    networks:
      - frontend
      - backnet
      - proxynet
      
  database:
    build:      
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_HOST_PORT}:8080"
    networks:
      - backnet

networks:
  proxynet:
    driver: bridge
  frontend:
    driver: bridge
  backnet:
    driver: bridge
  
volumes:
  postgres_data:
